### ISSUE TITLE
Lato rendering on Windows

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1198]
There are 2 suggestions based on customer-feedback i wanted to share.

__1 the Toggle to un/collapse Contentelements should be a bit louder__
https://github.com/contao/core-bundle/issues/678#issuecomment-284712415
![image](https://user-images.githubusercontent.com/4138336/33113746-0b638a58-cf5a-11e7-894f-024ca71b04eb.png)

I'd prefer to have it wider, with color and stuck to the bottom-border.
Maybe like this:
![image](https://user-images.githubusercontent.com/4138336/33114598-cc77157c-cf5d-11e7-800f-158b604779e1.png)

```diff
.limit_toggler button span {
    position: relative;
+++    top: -2px;
}
.limit_toggler button {
    margin: 0;
    padding: 0;
    border: 0;
+++    background: #589b0e;
+++    width: 27px;
+++    line-height: 9px;
+++    color: #fff;
    outline: 0;
+++    border-top-left-radius: 6px;
+++    border-top-right-radius: 6px;
}
.limit_toggler {
    width: 100%;
    position: absolute;
    bottom: 0;
    left: 0;
    background: #fff;
+++    line-height: 10px;
    text-align: center;
}
```

<hr>

__2 bring back contrast to legends__

it's difficult to find certain sections because of the light color and fontweight of the legends opposed to the following labels (which are bold and darker) especialy if these sections are uncollapsed.

![image](https://user-images.githubusercontent.com/4138336/33115099-fb2d2b16-cf5f-11e7-9a28-98a927afb8a9.png)

![image](https://user-images.githubusercontent.com/4138336/33115078-dbda7688-cf5f-11e7-8f97-58a8992c8f3c.png)

```diff
fieldset.tl_tbox>legend, fieldset.tl_box>legend {
    width: 100%;
    box-sizing: border-box;
+++    color: #589b0e;
    padding: 14px 0 0 28px;
    background: url(icons/navcol.svg) 13px 16px no-repeat;
    cursor: pointer;
+++    font-weight: 700;
}
```

**Comment by fritzmg** [comment]
Regarding visibility and contrast: the currently used back end font makes it difficult to distinguish (at a glance) between a regular and a bold font weight - at least under FireFox and Windows (10). The following text content element has 3 words highlighted in bold, but it is really hard to see which ones:

![screen-shot-2017-11-22-at-09 21](https://user-images.githubusercontent.com/4970961/33116844-9d3bb1ba-cf66-11e7-94d6-e19b6c2f79fb.png)

**Comment by leofeyer** [comment]
Sorry, but I won't adopt any of the suggested changes.

The "expand element" toggle is a lowest priority UI element, which most users never use (see the discussion about removing the big green arrows), therefore it must not be highlighted like this.

A similar argumentation applies to the section legends, which we have desaturated deliberately.

> between a regular and a bold font weight

Looks perfectly fine on my Mac, so this seems to be a Windows issue. Can anyone else reproduce?

**Comment by xchs** [comment]
> Can anyone else reproduce?

Yes, I can. Firefox | Chrome @ Windows 10.

**Comment by fritzmg** [comment]
Screenshot of Microsoft Edge 40.15063.674.0 (under Windows 10):

![msedge](https://user-images.githubusercontent.com/4970961/33124044-274671dc-cf7c-11e7-962e-730f3acf21c8.png)

**Comment by leofeyer** [comment]
Looks ok to me. What font-weight is it?

**Comment by fritzmg** [comment]
> Looks ok to me.

Were you really able to identify all 3 bold words at a glance in those screenshots?

> What font-weight is the bold text?

`700`

**Comment by xchs** [comment]
Two screenshots from Firefox:

* default:
![screenshot-2017-11-22-12-11-20](https://user-images.githubusercontent.com/1218766/33124909-f4bae0ce-cf7e-11e7-9e9c-00de3889b423.png)

* "Lato" removed from the font stack:
![screenshot-2017-11-22-12-12-00](https://user-images.githubusercontent.com/1218766/33124922-fe462de2-cf7e-11e7-86f2-b9b920dcff06.png)

**Comment by fritzmg** [comment]
> "Lato" removed from the font stack:

In this case your browser chose Arial as the fallback.

**Comment by xchs** [comment]
> (note) In this case your browser chose Arial as the fallback.

Nope, in my case it is actually "Roboto".

**Comment by fritzmg** [comment]
> Nope, in my case it is actually "Roboto".

Right, sorry. I assume this font is locally installed as TTF or OTF?

**Comment by leofeyer** [comment]
We are using [Lato 2.0](http://www.latofonts.com/lato-free-fonts/#download). Maybe there is a bug in the font files?

**Comment by xchs** [comment]
> I assume this font is locally installed as TTF or OTF?

Yep. But it does not matter anyway. I wanted to point out only how evident the difference is and how it could look when the contrast between regular and bold font is noticeable higher.

**Comment by fritzmg** [comment]
I just noticed that `themes/flexible/fonts.css` does not include any bold font styles from Lato. And both the `Medium` and `Semi Bold` font styles of Lato (which are included) are defined as having font-weight `700`. Medium should be `500` and Semi Bold should be `600`.

**Comment by leofeyer** [comment]
Where did you see `font-weight: 700` in the `fonts.css` style sheet?

**Comment by fritzmg** [comment]
```css
@font-face {
    font-family: "Lato";
    src: local("Lato Semibold"), url(fonts/Lato-Semibold.woff2) format("woff2"), url(fonts/Lato-Semibold.woff) format("woff");
    font-weight: 700;
    font-style: normal;
    text-rendering: optimizeLegibility
}
```

**Comment by leofeyer** [comment]
It seems that the minifier has changed this, because it is not in the un-minified file:

https://github.com/contao/core-bundle/blob/4.4.8/src/Resources/contao/themes/flexible/src/fonts.css

**Comment by ausi** [comment]
`font-weight:bold` and `font-weight:700` is the same in CSS, but `700` is one byte shorter than `bold` :)

**Comment by fritzmg** [comment]
Yes, but the point is, `Lato-Semibold` is used for the font-weight of `700` in the Contao backend, instead of `600`, while `Lato-Bold` should be used for the actual font-weight of `700`. This would presumably make bold text be more distinguishable from regular text (under Windows at least).

**Comment by leofeyer** [comment]
@fritzmg Can you exchange Lato-Semibold with Lato-Bold and make another screenshot please?

**Comment by fritzmg** [comment]
Definitely better:

![ff](https://user-images.githubusercontent.com/4970961/33132962-8a783924-cf9b-11e7-813e-4bcc4c46bfe2.png)

Still not as clear as @xchs ' Roboto example though. While I do like the font _Lato_ in general, may be it's not really suitable for this.

How does such an example look like on OSX or Linux?

**Comment by leofeyer** [comment]
I can only tell you how it looks with a retina display:

<img width="766" alt="" src="https://user-images.githubusercontent.com/1192057/33133788-2c3da814-cf9e-11e7-8c3a-1348382dd466.png">

This is Lato-Light and Lato-Medium BTW.

**Comment by fritzmg** [comment]
Yeah, the problem is more that the Regular font face of Lato renders so badly on Windows.

**Comment by leofeyer** [comment]
Well that is not Contao's fault, is it? Although, hasn't Lato improved their Windows support in [version 1.104](http://www.latofonts.com/2011/11/08/lato-version-1-104/)?

**Comment by leofeyer** [comment]
BTW, the Contao Manager also uses Lato. Does this render badly, too? Is there a difference when you use the Lato fonts provided by Google fonts?

**Comment by fritzmg** [comment]
> Well that is not Contao's fault, is it?

No, but Contao uses Lato, hence the problems with readability ;)

I'll make some tests regarding Google Fonts.

**Comment by asaage** [comment]
I have the same font-experience like @fritzmg we had a similar issue last year with the Roboto-font https://github.com/contao/core-bundle/issues/590

Should this issue be renamed? It has little to with the initial post.

**Comment by Aybee** [comment]
Lato also looks a bit blurred on Windows. In a test all other families look more sharp (better).

- Roboto
- Verdana
- Tahoma
- Arial

**Comment by fritzmg** [comment]
Test results: https://dev.inspiredminds.at/lato/ (there are Screenshots below)

I cannot make a comparison between http://www.latofonts.com and Google Fonts for `Lato SemiBold`, because Google Fonts does not provide `Lato SemiBold`.

Generally the `Lato` family looks vastly different when loaded from Google. It does not really look better.

**Comment by leofeyer** [comment]
Thank you @fritzmg. I'm going to replace "Lato SemiBold" with "Lato Bold" then for non-retina displays.

**Comment by dmolineus** [comment]
Sidenote: Webfonts, also Google Fonts, often performs bad on Windows in general...

**Comment by leofeyer** [comment]
I have also tried to use system fonts (something like `-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`), however, it just looks clunky – especially on a retina display.

**Lato**

<img width="1024" alt="" src="https://user-images.githubusercontent.com/1192057/33285384-6d5c3096-d3b2-11e7-96df-82c3b69bf157.png">

**System font**

<img width="1024" alt="" src="https://user-images.githubusercontent.com/1192057/33285399-78e02418-d3b2-11e7-8301-afa56615d2b6.png">

@fritzmg Can you upload a screenshot of how the back end looks on Windows with the font family above?

**Comment by bekanntmacher** [comment]
and what about open sans https://en.wikipedia.org/wiki/Open_Sans ?

**Comment by leofeyer** [comment]
That's not up for discussion. Right now we are using Lato everywhere, so it is either no web fonts at all or Lato.

**Comment by fritzmg** [comment]
> @fritzmg Can you upload a screenshot of how the back end looks on Windows with the font family above?

![screen shot 2017-11-28 at 10 12 22](https://user-images.githubusercontent.com/4970961/33311313-b78a3a74-d424-11e7-8a3e-0f137d47d086.png)

Obviously `Segoe UI` is used in this case under Windows. Doesn't look that great.

**Comment by leofeyer** [comment]
Fixed in 8762e740e97153597a79e516aa2e7755c811335b.

**Comment by fritzmg** [comment]
This issue is back again. Contao's TinyMCE skin for Contao 4.4.x uses the following font-face definitions:
```css
@font-face {
	font-family: "Lato";
	src: local("Lato Semibold"), url(fonts/Lato-Semibold.woff2) format("woff2"), url(fonts/Lato-Semibold.woff) format("woff");
	font-weight: 700;
	font-style: normal;
	text-rendering: optimizeLegibility
}

@font-face {
	font-family: "Lato";
	src: local("Lato Semibold Italic"), url(fonts/Lato-SemiboldItalic.woff2) format("woff2"), url(fonts/Lato-SemiboldItalic.woff) format("woff");
	font-weight: 700;
	font-style: italic;
	text-rendering: optimizeLegibility
}
```
It again uses Semibold instead of Bold.

https://github.com/contao-components/tinymce4/blob/40933994137ae78f88f4f3c336bb80fa81f33d7d/js/skins/contao/content.min.css#L1

**Comment by leofeyer** [comment]
It seems you have a very outdated version (4.6?) of TinyMCE.

**Comment by fritzmg** [comment]
That's what Contao 4.4.x uses: https://github.com/contao/contao/blob/c1026282f5e53046501b0b07b578ad722fceab80/core-bundle/composer.json#L37

Newer versions of `contao-components/tinymce4` would be (sort of) incompatible with Contao 4.4, due to the different font stack.

**Comment by leofeyer** [comment]
I have just released [version 4.6.7.3](https://github.com/contao-components/tinymce4/compare/4.6.7.2...4.6.7.3) of the component.
