### ISSUE TITLE
Missing request token in form when maintenance mode is enabled

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#1370]
Tested on Contao 4.4.13 and 4.4.14.

- Set up a form with several mandatory fields and disable HTML5 validation.
- Include the form on a page
- Go to the page and view the source code, the request token is empty 
(`<input name="REQUEST_TOKEN" value="" type="hidden">`)

Disable the maintenance mode and it works like a charm.

**Comment by leofeyer** [comment]
Does the issue occur in Contao 4.5 as well?

**Comment by netzarbeiter** [comment]
I have now set up two new blank installations 4.4.14 and 4.5.4, in both the value of the request token remains empty when the maintenance mode is enabled.

**Comment by ausi** [comment]
It seems that the ESI fragment for the request token returns an empty string, maybe because the maintenance mode changes the status code to something different than `200`?

**Comment by netzarbeiter** [comment]
I get status `200` with and without maintenance mode enabled.

**Comment by Toflar** [comment]
Yes, the maintenance mode listener returns a `503` for any request. It also does so for ESI requests and that's why the data is hidden. That listener should be disabled for fragments.

The config.yml should be adjusted from 

```yaml
lexik_maintenance:
    authorized:
        path: ^/contao($|/)
        attributes:
           _bypass_maintenance: true
```
to this
```yaml
lexik_maintenance:
    authorized:
        path: '^(/contao($|/))|(%fragment.path%)'
        attributes:
           _bypass_maintenance: true
```

Completely untested but you get the point.

**Comment by leofeyer** [comment]
Can you please try again to reproduce the issue with the latest `4.4` branch? I have merged the HTTP cache fixes and I made sure that the page is cached:

```php
<input type="hidden" name="REQUEST_TOKEN" value="<?php echo $this->surrogate->handle($this, '/_fragment?_path=insertTag%3D%257B%257Brequest_token%257D%257D%26_format%3Dhtml%26_locale%3Den%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=900&pageId=62&request=en%2Fapplications.html&_hash=qZBuTWT1ZeiB61Aq2KtbEISyMmAwHroZwSH8%2BkACbhU%3D', '', true) ?>
```

Then I have enabled the maintenance mode, logged in to the back end and opened the front end preview. The request token was never blank. 🤔

**Comment by netzarbeiter** [comment]
I have installed `4.4.x-dev aa00b1c` still the same behaviour, empty value field and after clicking send the Invalid request token-page shows up. Do you want access to my test case?

**Comment by leofeyer** [comment]
No, but a bit more information if you don't mind. Do you use the official demo? Which cache timeout have you configured?

**Comment by Toflar** [comment]
@netzarbeiter sent me access details so I could check on his system and here's the reason why it doesn't work (and it cannot work on your system either, no idea why you cannot reproduce this).

The problem is that our `BypassMaintenanceListener` in version 4.4 does this:

https://github.com/contao/core-bundle/blob/4.4/src/EventListener/BypassMaintenanceListener.php#L76-L92

This does not work for a "subrequest" (in quotes because it is a subrequest but it's a **master** subrequest as it's an ESI request), because a subrequest is internal and `$request->getClientIp()` correctly returns `127.0.0.1` in that case causing the hash not to match the cookie anymore.

In 4.5, we have a different check there because of the new authentication mechanisms but I guess it also fails there because `/_fragment` is not protected by any firewall and thus you don't have any user. But that's good, `/_fragment` doesn't need to be protected because it's URI signed so you can never tamper with the parameters.

My solution to this remains the same and works perfectly fine:

```yaml
lexik_maintenance:
    authorized:
        path: '^(/contao($|/))|(%fragment.path%)'
        attributes:
           _bypass_maintenance: true
```

**Comment by leofeyer** [comment]
> no idea why you cannot reproduce this

You have just explained it. 😄 `$request->getClientIp()` returns `127.0.0.1` upon an internal request and that exactly matches the my IP address on my local system. Therefore `hasAuthenticatedBackendUser()` always returns `true`.

However, I think we should use one of the following expressions:

 * `'^(/contao($|/))|(%fragment.path%($|/))'`
 * `'^((/contao)|(%fragment.path%))($|/)'`

Because `%fragment.path%` translates to `/_fragment` and this would also match `/_fragmenting`, wouldn't it?

**Comment by leofeyer** [comment]
Or – as described in the [Lexik maintenance documentation](https://github.com/lexik/LexikMaintenanceBundle/blob/master/Resources/doc/index.md#use) – we should probably add `ips: ['127.0.0.1']`.

**Comment by leofeyer** [comment]
I have verified that `ips: ['127.0.0.1']` also fixes the issue. Any objections?

**Comment by Toflar** [comment]
We should add 127.0.0.1 for sure but also fragment path, otherwise it would not work for Varnish and Co.

**Comment by leofeyer** [comment]
Why would it not work? Does Varnish use a different IP address than `127.0.0.1`?

**Comment by Toflar** [comment]
It may? Sure!

**Comment by leofeyer** [comment]
@contao/developers Are we 100% sure that whitelisting all fragment requests does not have any side effects?

**Comment by Toflar** [comment]
"whitelisting all fragment requests" is the same thing as "disabling the maintenance listener for fragment requests". Nothing else. It has no effects on any other component, it's only about this one `kernel.request` listener. So I am 100% sure there are no side effects.

The question is not about side effects, it's just the question whether it's okay that fragment requests can still be accessed during maintenance mode. It would also affect `hinclude` elements for example. Thinking about this, here's an example:

Let's say we have 100% of the page that is cacheable except for a cart module. This is included using hinclude to leverage private caching (and to widen our horizon, we should not only think about ESI). So if I would enable the maintenance mode, what would happen is that the main page gets into maintenance mode and the cart module is still displayed normally. This indeed sounds strange. However, right now, the main page gets into maintenance mode and the cart module returns an empty response (because everything that's not `200 OK` is ignored). Or well, you'll get it from your cache so the cart might still be displayed. That doesn't sound a lot better to me either, does it?

Not sure if there's even a good solution for that problem for `hinclude`.
For `esi` we may go with the `ips` solution but they should map to the trusted proxies in my opinion (which should be a setting in the maintenance bundle for convenience imho), so I could add Varnish to my trusted proxies (which I have to do anyway).

I think we should put that up for discussion for April, 12th.

**Comment by netzarbeiter** [comment]
An easy way to reproduce it, add `{{date::Y}}` to an article. No output when maintenance mode is enabled.

**Comment by leofeyer** [comment]
See #1476.
