### ISSUE TITLE
4.4.15+ BackendController::pickerAction route will end in frontend scope

### ISSUE THREAD

**Issue by fatcrobat** [contao/core-bundle#1418]
In Contao 4.4.14 the picker is still working, but stopped working for us with version 4.4.15. 

**The route annotation in 4.4.14 for method `pickerAction` was:**

```
@Route("/_contao/picker", name="contao_backend_picker")
```

The url `app_dev.php/_contao/picker?context=link&extras[fieldType]=radio&extras[filesOnly]=true&value=&popup=1` will trigger a 302 RedirectException and the route is assigned to `backend` scope.

**From 4.4.15 on the annotation changed to:**

```
@Route("/contao/picker", name="contao_backend_picker")
```

The url `app_dev.php/_contao/picker?context=link&extras[fieldType]=radio&extras[filesOnly]=true&value=&popup=1` will now trigger a 404 Exception, because the route is assigned to `frontend` scope.

I first discovered this behaviour when using the tinyMCE link picker:
![backend-picker](https://user-images.githubusercontent.com/480054/37166677-f3f9e228-22ff-11e8-9f39-d562f354b073.png)

**Comment by fritzmg** [comment]
This is already fixed in Contao 4.4.16

**Comment by fatcrobat** [comment]
@fritzmg Not for me. Updated to 4.4.16 and removed /var/cache folder, still getting a 404:


```
contao/core-bundle                                4.4.16      ! 4.5.6       Contao 4 core bundle
```
*composer show -l | grep core-bundle*

![backend-picker](https://user-images.githubusercontent.com/480054/37166970-d8a6406a-2300-11e8-9e64-19d582aa0368.png)

**Comment by leofeyer** [comment]
This is fixed in Contao 4.4.16 (see 4f6cbc4320734abcb791d3349196f83c8373c180). I assume you have a browser cache problem.

**Comment by fatcrobat** [comment]
@leofeyer You were right, sometimes i hate that client cache!
