### ISSUE TITLE
ce_gallery: wrong anchor-title for linked images

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1444]
This might be a follow-up on #947 which was closed as invalid but there is something going wrong here.
The title attribute of the anchor in a ce_gallery is only correct if you **don't** add link-Meta data in the File manager.
Compare **ce_image** (block 1)
with **ce_gallery with meta link** (block 2)
and **ce_gallery without meta link** (block 3)

Another thing is the title-attribute on the image itself - which i think is useless and doesn't even show up in block 3

```html
<div class="ce_image first block">
  <figure class="image_container" itemscope itemtype="http://schema.org/ImageObject" itemprop="associatedMedia">
    <a href="my-link" title="my-title" target="_blank" itemprop="contentUrl">
      <img src="files/a/my_image.jpg" width="800" height="720" alt="my-alt" itemprop="image">
    </a>
    <figcaption class="caption" itemprop="caption">my-caption</figcaption>
  </figure>
</div>

<div class="ce_gallery block">
  <ul class="cols_1" itemscope itemtype="http://schema.org/ImageGallery">
    <li class="row_0 row_first row_last even col_0 col_first col_last">
      <figure class="image_container" itemscope itemtype="http://schema.org/ImageObject">
        <a href="my-link" title="my_image.jpg" itemprop="contentUrl">
          <img src="files/a/my_image.jpg" width="800" height="720" alt="my-alt" title="my-title" itemprop="image">
        </a>
        <figcaption class="caption" itemprop="caption">my-caption</figcaption>
      </figure>
    </li>
  </ul>
</div>

<div class="ce_gallery block">
  <ul class="cols_1" itemscope itemtype="http://schema.org/ImageGallery">
    <li class="row_0 row_first row_last even col_0 col_first col_last">
      <figure class="image_container" itemscope itemtype="http://schema.org/ImageObject">
        <a href="files/a/my_image.jpg" data-lightbox="lb418" title="my-title" itemprop="contentUrl">
          <img src="files/a/my_image.jpg" width="800" height="720" alt="my-alt" itemprop="image">
        </a>
        <figcaption class="caption" itemprop="caption">my-caption</figcaption>
      </figure>
    </li>
  </ul>
</div>
```
![image](https://user-images.githubusercontent.com/4138336/38005575-896a8902-3241-11e8-93b5-d922e2682723.png)

**Comment by fritzmg** [comment]
I agree that it should be more consistent.

However, if you change it so that the `title` is always only shown on the `<img>` and not on the `<a>` (if you did not provide a meta link), then Contao's core lightbox solutions will not display the title in the lightbox anymore, since they expect the title to be in the `<a>`.

**Comment by asaage** [comment]
absolutely in ```<a>```

**Comment by fritzmg** [comment]
> absolutely in <a>

Why? The title for the image should be on the image, shouldn't it? ;)

**Comment by asaage** [comment]
1st: you already mentioned the lightbox (not only Contao's core lightbox)
2nd: what's the purpose of title in image? screenreaders should use ```alt``` mouse-users would usually see the title of ```<a>``` anyway  ;)

**Comment by fritzmg** [comment]
> 2nd: what's the purpose of title in image? screenreaders should use alt mouse-users would usually see the title of <a> anyway ;)

`alt` and `title` are completely different things.

`alt` is the _alternative_ text for the image, which is shown instead of the image when not available or used in a textual context (screen reader, content parsing, etc.).

`title` is an additional meta data property for _any_ HTML element, including images.

The contents of these attributes simply depends on the image and how the image is used. In a gallery, you typically would only need the `alt` attribute, since it probably does not make sense to provide any additional meta information about the image in the `title` attribute - and it does not make sense to just repeat the same text in the `title` attribute.

**Comment by leofeyer** [comment]
How can I reproduce the initial problem?

**Comment by asaage** [comment]
- create a gallery
- enable "Full-size view/new window (Open the full-size image in a lightbox or the link in a new browser window.)"
- make shure at least one image has link and title in meta-data

**Comment by leofeyer** [comment]
This was not really an extensive description, so all I can do is guess what you could have meant. Here is the HTML output of the gallery elements with and without a meta link:

**Without meta link**

```html
<figure class="image_container" itemscope itemtype="http://schema.org/ImageObject">
  <a href="files/contaodemo/media/content-images/DSC_5276.jpg" data-lightbox="lb290" title="my-title" itemprop="contentUrl" class="cboxElement">
    <img src="assets/images/6/DSC_5276-cca4e16e.jpg" width="300" height="200" alt="my-alt" itemprop="image">
  </a>
  <figcaption class="caption" itemprop="caption">my-caption</figcaption>
</figure>
```

**With meta link**

```html
<figure class="image_container" itemscope itemtype="http://schema.org/ImageObject">
  <a href="my-link" target="_blank" title="my-title" itemprop="contentUrl">
    <img src="assets/images/6/DSC_5276-cca4e16e.jpg" width="300" height="200" alt="my-alt" itemprop="image">
  </a>
  <figcaption class="caption" itemprop="caption">my-caption</figcaption>
</figure>
```

In both cases all meta attributes are set correctly.

**Comment by leofeyer** [comment]
Now I can reproduce it.

**Comment by leofeyer** [comment]
Fixed in c174cafdb63dc6d2b492bf940632758c17992f96.

**Comment by Aybee** [comment]
This still does not work in Contao 4.4.

**Usecase**:

A gallery with some images.

Some images in the gallery have a link set in file manager.

Now if you hover over the image in front end you should see the link text|alias (or page title) if the image has a link set. (Also if a title is set.)

It should show the image name (or title if set) if a link is not set.

At the moment in both cases it shows the images name. (Leave the title field blank.)
