### ISSUE TITLE
is_link under windows returns always false

### ISSUE THREAD

**Issue by Zeromax** [contao/core-bundle#460]
This line will not work on windows and therefore the installation tool will generate all the symlinks again which are already created:
https://github.com/contao/installation-bundle/blob/master/src/Controller/InstallationController.php#L117

Look here for a workaround:
https://github.com/contao-community-alliance/composer-plugin/issues/34

I propose this solution:
```php
if (is_dir($rootDir . '/../files') && is_link($rootDir . '/../web/assets')) {
    return;
} elseif (defined('PHP_WINDOWS_VERSION_BUILD')
    && is_dir($rootDir . '/../files')
    && file_exists($rootDir . '/../web/assets')
    && readlink($rootDir . '/../web/assets') == dirname($rootDir) . DIRECTORY_SEPARATOR . 'assets') {
    return;
}
```

**Comment by discordier** [comment]
ref: https://bugs.php.net/bug.php?id=65697

**Comment by leofeyer** [comment]
Which PHP version are you using?

**Comment by Zeromax** [comment]
> PHP 5.6.12 (cli) (built: Aug  6 2015 12:06:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by Zeromax** [comment]
So to be sure that my proposal is working...
Today I have done the following:
1. delete all content from the vender Folder
2. Start CMD with Admin Rights
3. Run `composer install`
4. Add the fix above to the InstallationController
5. Call the install.php -> all bundle symlinks were created as needed

**Comment by Zeromax** [comment]
@leofeyer why are you closing this? It is still not fixed

**Comment by leofeyer** [comment]
Sorry. Are the links created as `<JUNCTION>` or as `<SYMLINKD>`?

**Comment by Zeromax** [comment]
No Problem.
They are `<SYMLINKD>`.
![unbenannt](https://cloud.githubusercontent.com/assets/1867177/13888219/7c861af0-ed40-11e5-8c57-e6e1d9b7275a.PNG)

**Comment by leofeyer** [comment]
`is_link()` should work with `<SYMLINKD>` (see the discussion at contao-community-alliance/composer-plugin#34).

**Comment by Zeromax** [comment]
I have opened this issue cause it does not work.
Symlink creation does work, but testing with is_link does not work.

Read https://bugs.php.net/bug.php?id=65697

> [2013-09-18 20:34 UTC] giunta dot gaetano at gmail dot com
Ok, then be it

It is still not resolved. If it works with php 7? I do not now.

**Comment by leofeyer** [comment]
Why do you keep linking the PHP bug report? It is about junctions only.

**Comment by Zeromax** [comment]
Resolved with fcgi:
https://github.com/contao/core-bundle/issues/208#issuecomment-138114929

**Comment by backbone87** [comment]
this issue still occurs on PHP 5.6.28 when ran as mod_php in apache 2.4 on windows

is_link (and lstat) RANDOMLY return true or false for symlinks. the symlinks are <SYMLINKD> and created with admin rights.

readlink always works, and correctly reads the link.

when using the builtin webserver, started from a (non-elevated) CLI, this problem does NOT occur.

and according to @Zeromax fcgi (and probably fpm/cgi) does not have this problem

**Comment by backbone87** [comment]
just tested it with PHP 7.0.13 mod_php apache 2.4 win and it works there

**Comment by backbone87** [comment]
ping?
